/* ============================================================
   Scholarics Service Worker v2.0
   Strategy: Cache-first for shell assets, network-first for HTML,
   offline fallback page for navigation failures.
   ============================================================ */

var CACHE_NAME = 'scholarics-shell-74ecdde1'; /* bumped: gpa-simulator now includes ai-service + ai-assistant bundles */
var OFFLINE_URL = '/404.html';

/* Assets to pre-cache on install (the app shell).
   GENERATED by tools/build-assets.mjs — do not edit by hand.
   Fingerprinted bundles contain:
     /assets/css/core.a1dcaabc.css  ←  /css/style.css, /css/premium.css, /css/personalization.css, /css/content-platform.css
     /assets/css/shell.cc3a5b31.css  ←  /css/consent.css, /css/scholarics-v2.css, /css/sc-prelaunch-fixes.css
     /assets/js/g-ca0b60.b6d910de.js  ←  /js/script.js, /js/personalization.js, /js/premium.js, /js/sc-shell.js, /js/sc-v2-features.js, /js/analytics.js, /js/consent.js, /js/email-capture.js, /js/pwa.js
     /assets/css/core-3.06a13263.css  ←  /css/style.css, /css/premium.css, /css/personalization.css
     /assets/js/core-shell-person-prem-ga-consent-pwa.f136b6c8.js  ←  /js/script.js, /js/sc-shell.js, /js/personalization.js, /js/premium.js, /js/analytics.js, /js/consent.js, /js/pwa.js
     /assets/css/calc-ai.c05aaeec.css  ←  /css/calculators.css, /css/ai-assistant.css
     /assets/js/core.d3fc79e1.js  ←  /js/script.js
     /assets/js/p-gpa-simulator.a69a812f.js  ←  /js/share-links.js
     /assets/js/g-a35680.7c77dde5.js  ←  /js/calculators.js, /js/personalization.js, /js/premium.js, /js/sc-shell.js, /js/sc-v2-features.js, /js/analytics.js, /js/consent.js, /js/email-capture.js, /js/pwa.js
     /assets/js/p-gpa-simulator-2.025fbc7d.js  ←  /js/gpa-simulator-core.js, /js/gpa-simulator.js
     /assets/js/p-aisvc-assist.a2b31c07.js  ←  /js/ai-service.js, /js/ai-assistant.js
*/
var SHELL_ASSETS = [
  '/',
  '/index.html',
  '/404.html',
  '/gpa-simulator.html',
  '/images/favicon.svg',
  '/assets/css/core.a1dcaabc.css',
  '/assets/css/shell.cc3a5b31.css',
  '/assets/js/g-ca0b60.b6d910de.js',
  '/assets/css/core-3.06a13263.css',
  '/assets/js/core-shell-person-prem-ga-consent-pwa.f136b6c8.js',
  '/assets/css/calc-ai.c05aaeec.css',
  '/assets/js/core.d3fc79e1.js',
  '/assets/js/p-gpa-simulator.a69a812f.js',
  '/assets/js/g-a35680.7c77dde5.js',
  '/assets/js/p-aisvc-assist.a2b31c07.js',
  '/assets/js/p-gpa-simulator-2.025fbc7d.js'
];

self.addEventListener('install', function (e) {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(SHELL_ASSETS).catch(function () {
        /* Non-fatal: if a shell asset fails, install still succeeds */
      });
    })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.filter(function (k) { return k !== CACHE_NAME; })
            .map(function (k) { return caches.delete(k); })
      );
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  var req = e.request;

  /* Only handle GET requests to same origin */
  if (req.method !== 'GET' || !req.url.startsWith(self.location.origin)) return;

  /* API calls: always network-only, no caching */
  if (req.url.includes('/api/')) return;

  /* HTML navigation: network-first, fallback to offline page */
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req).catch(function () {
        return caches.match(OFFLINE_URL);
      })
    );
    return;
  }

  /* Static assets: cache-first.
     ignoreSearch:true means css/style.css?v=2.1 hits the same cache entry
     as /css/style.css, so version-bumped query strings bust the network
     fetch path without creating duplicate cache entries. */
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(function (cached) {
      if (cached) return cached;
      return fetch(req).then(function (res) {
        if (!res || res.status !== 200) return res;
        var clone = res.clone();
        /* Store under the bare path (no query string) so future requests
           with any ?v= value can match it via ignoreSearch. */
        var storeReq = new Request(req.url.split('?')[0]);
        caches.open(CACHE_NAME).then(function (cache) { cache.put(storeReq, clone); });
        return res;
      });
    })
  );
});
