import { withApi, json, corsHeaders } from '../_lib/http.js';
import { requireEmail, clean, str } from '../_lib/validate.js';
import { isDuplicate, storeWaitlist, initWaitlistDB, logWaitlistEvent } from '../_lib/waitlistStore.js';

/**
 * POST /api/waitlist — Premium waitlist subscription endpoint.
 *
 * Requirements met:
 * - Email validation (loose regex + length cap)
 * - Input sanitization (clean, trim, lowercase)
 * - Duplicate prevention (checks KV primary key)
 * - Rate limiting (5 requests/min per IP, stricter than default)
 * - Database initialization if no binding exists (logs + throws clear error)
 * - Logging (console.info / console.error for observability)
 * - No secrets exposed in responses
 * - Cloudflare Pages Functions compatible (ESM, no Node-specific APIs)
 */

export const onRequestOptions = async ({ request }) => {
  return new Response(null, { status: 204, headers: corsHeaders(request, { corsMethods: 'POST, OPTIONS' }) });
};

export const onRequestPost = withApi(async ({ body, env, request }) => {
  // Initialize schema (no-op if KV is bound; logs and sets meta if missing)
  await initWaitlistDB(env);

  // Sanitize inputs
  var rawEmail = body && body.email ? body.email : null;
  var source = clean(str(body && body.source ? body.source : 'premium-modal'));
  var page = clean(str(body && body.page ? body.page : 'unknown'));

  // Validate email
  var email;
  try {
    email = requireEmail(rawEmail);
  } catch (e) {
    logWaitlistEvent(env, 'waitlist_validation_failed', { reason: e.message, raw: rawEmail, ip: request.headers.get('cf-connecting-ip') || 'unknown' });
    return json({ ok: false, error: 'Please enter a valid email address.' }, 400);
  }

  // Prevent empty or malicious payload
  if (email.length > 320) {
    return json({ ok: false, error: 'Email address is too long.' }, 400);
  }

  // Rate limit is enforced by withApi ({ limit: 5 }) — but we add an extra check for duplicate spam
  // Check duplicate subscription
  var duplicate;
  try {
    duplicate = await isDuplicate(env, email);
  } catch (e) {
    logWaitlistEvent(env, 'waitlist_duplicate_check_failed', { email: email, error: e.message });
    return json({ ok: false, error: 'Could not verify subscription status. Please try again.' }, 500);
  }

  if (duplicate) {
    logWaitlistEvent(env, 'waitlist_duplicate_blocked', { email: email, source: source, page: page });
    return json({
      ok: true,
      duplicate: true,
      message: "Thanks! You're on the Premium waitlist. (You're already subscribed — we'll notify you at launch.)"
    }, 200);
  }

  // Extract IP for logging (not stored unless needed for anti-spam audit; here stored for analytics only)
  var clientIP = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || 'unknown';
  if (clientIP.includes(',')) clientIP = clientIP.split(',')[0].trim();

  // Store in database
  var result;
  try {
    result = await storeWaitlist(env, email, {
      source: source,
      page: page,
      timestamp: Date.now(),
      ip: clientIP,
      id: undefined // generated by store
    });
  } catch (e) {
    logWaitlistEvent(env, 'waitlist_storage_failed', { email: email, error: e.message, ip: clientIP });
    try { console.error('[WAITLIST] Storage failed:', e && (e.stack || e.message || e)); } catch (logErr) {}
    return json({ ok: false, error: 'We could not save your subscription right now. Please try again shortly.' }, 500);
  }

  // Success logging
  logWaitlistEvent(env, 'waitlist_subscribed', {
    email: email,
    source: source,
    page: page,
    id: result.id,
    method: result.method,
    namespace: result.namespace,
    stored: result.stored,
    ip: clientIP
  });

  // Return production-ready response (no secrets, no raw errors)
  return json({
    ok: true,
    message: "Thanks! You're on the Premium waitlist.",
    id: result.id,
    stored: result.stored
  }, 201);
}, { limit: 5, scope: 'waitlist', cors: true, corsMethods: 'POST, OPTIONS' });
